language: node_js
node_js:
 - "8"
 - "10"
 - "12"
 - "lts/*"
 - "node"

before_script:
  - npm run build

script:
  - npm test
  - npm run spec
cache:
 - npm
 - directories:
   - .rdf-test-suite-cache
